### ISSUE TITLE
Olomastering won't work

### ISSUE THREAD

**Issue by jean-n92** [azufre451/startrekfederation#19]
Nonostante i nostri migliori sforzi, l'olomastering non funziona. Sembra riuscire a mandare le immagini, ma non le stringhe normali. Consultare la schermata allegata per una preview.
<img width="1034" alt="Schermata 2021-04-01 alle 20 16 43" src="https://user-images.githubusercontent.com/57634402/113336782-2f35e180-9327-11eb-9ce7-68c556db9e43.png">

**Comment by jean-n92** [comment]
Dear @jean-n92 , 
Thanks for your report! This ticket has been assigned to @azufre451.
The expected completion time is ```Nan```.

Have a nice day,
Gian

**Comment by azufre451** [comment]
Fatto, problema di variabile vuota che creava problemi da quando usiamo l'escape speciale per il parlato in masterata (~18 giorni fa).

Risistemato a come era prima per la parte olomaster.
