### ISSUE TITLE
[Feature]Master

### ISSUE THREAD

**Issue by Seifer1987** [azufre451/startrekfederation#24]
**Descrivi la feature**
La mia idea sarebbe quella di aggiungere un pannellino Master con i suoni piú comuni da poter usare o mandare durante le role con un semplice click. Ad esempio colpi di phaser, suoni di plancia, fischio di plancia, suono di comm in entrata e comunque suoni canon tanto per capirci. Suoni brevi ovviamente che peró a mio avviso creano sicuramente un atmosfera piú immersiva.

**Descrivi la situazione attuale**
Li metto manualmente

**Note**
Mi odierete parte 2.

**Comment by azufre451** [comment]
Direi che questo sarebbe più una questione legata all'uso che fanno i master dei suoni di ambiente. Magari creiamo una soundbase di ambiente su Sigma, mi sembra il modo più sensato per affrontare questo problema!
