### ISSUE TITLE
Il paradosso dello staffer

### ISSUE THREAD

**Issue by Seifer1987** [azufre451/startrekfederation#29]
**Descrivi il bug**
Mi si presenta un bug peculiare, come ogni inizio settimana, il tool presenza staff mi si presenta con la sua solita scritta rossa e piuttosto minacciosa... peccato che io non sia inserito nella lista presenza staff con il mio nuovo pg XD Quindi, mi rimane sostanzialmente... li, senza poter fare nulla... aiuto?

**Steps per riprodurre il bug**
Spiegaci come riprodurre il bug che hai riscontrato:

1. Vai su '...'
2. Clicca su '....'
3. Scorri fino a '....'
4. Vedi l'errore

**Comportamento atteso**
Una spiegazione chiara e concisa di quale era il comportamento atteso.

**Screenshots**
Se puoi, allega uno screenshot

**Desktop (per favore specifica):**
 - Sistema Operativo: [es. Windows 10]
 - Browser [es. Chrome, Safari]
 - Versione [es. 22]

**Smartphone (specifica quale):**
 - Tipo: [es. Android / Apple]
 - Browser [es. stock-browser, Safari, Opera]

**Note aggiuntive**
Specifica ogni ulteriore dettaglio che possa aiutarci ad identificare il bug

**Comment by azufre451** [comment]
Non era un bug, c'era semplicemente un problema di allineamento del DB che pensava ancora lo staffer fosse il tuo vecchio PG. 
 ✅ Sistemato!
