### ISSUE TITLE
Incorrect TAG on Calendar

### ISSUE THREAD

**Issue by Cole0283** [azufre451/startrekfederation#31]
When you add a session in the calendar, the TAG included are of the previous session.

Go to Calendar, add a session. If you Insert Engineering TAG and the previous role is Tagged as Quest, the session will be added as Quest, not Engineering.

Tested on W10, Chrome last version.

**Comment by azufre451** [comment]
A posto. Ho cambiato il modo in cui l'evento appena creato veniva ricercato per caricarci le categorie nella query successiva.

Grazie!
